# Generated by Django 3.2.15 on 2022-08-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
