# Generated by Django 3.2.15 on 2022-08-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_comment_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='test',
        ),
    ]
