# Generated by Django 3.2.15 on 2022-08-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role1',
            field=models.CharField(default='Manager', max_length=20),
        ),
    ]
