# Generated by Django 3.2.15 on 2022-08-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_userprofile_role1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role1',
        ),
    ]
