# Generated by Django 3.2.15 on 2022-08-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_userprofile_role1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='role1',
            new_name='role',
        ),
    ]
