# Generated by Django 3.2.15 on 2022-08-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_role1_userprofile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
